
package-mode = false

[project]
name = "askdb"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "openai>=1.68.2",
    "sqlalchemy>=2.0.39",
    "sqlparse>=0.5.3",
    "streamlit>=1.43.2",
]
